elasticsearch:
  image: elasticsearch
  volumes:
    - '/data/elasticsearch:/usr/share/elasticsearch/data'
  ports:
    - '9200'

logstash:
  image: logstash
  command: 'logstash -e ''input { syslog { port => 5140 type => "docker" } } output { elasticsearch { host => "elasticsearch" } } filter { kv {} }'''
  ports:
    - '5140:5140/udp'
  links:
    - 'elasticsearch:elasticsearch'

kibana:
  image: kibana
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
    - '5601:5601'
  links:
    - 'elasticsearch:elasticsearch'
